openapi: 3.1.0
info:
  title: Simple Library Borrowing System - Guards API
  version: 1.0.0
  description: API for managing guards (librarians) who can manage books, members, and borrowings.

servers:
  - url: http://localhost:3000/api

tags:
  - name: Guards
    description: Endpoints related to guards (librarians)
  - name: Books
    description: Endpoints for managing books

paths:
  /guards/register:
    post:
      tags:
        - Guards
      summary: Register new guard
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RegisterGuardRequest"
      responses:
        "201":
          description: Guard created successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DataGuardResponse"
        "400":
          description: Bad request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

  /guards/login:
    post:
      tags:
        - Guards
      summary: Login guard
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/LoginGuardRequest"
      responses:
        "200":
          description: Login successful, return access token
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DataLoginResponse"
        "400":
          description: Bad request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

  /guards/me:
    get:
      tags:
        - Guards
      summary: Get current logged-in guard
      security:
        - ApiKeyAuth: []
      responses:
        "200":
          description: Guard profile
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DataGuardResponse"
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

    patch:
      tags:
        - Guards
      summary: Update current guard profile
      security:
        - ApiKeyAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UpdateGuardRequest"
      responses:
        "200":
          description: Updated guard data
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DataGuardResponse"
        "400":
          description: Bad request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

  /guards/logout:
    delete:
      tags:
        - Guards
      summary: Logout guard
      security:
        - ApiKeyAuth: []
      responses:
        "204":
          description: Logout successful (no content)
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

  /books:
    post:
      tags:
        - Books
      summary: Create new book
      security:
        - ApiKeyAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateBookRequest"
      responses:
        "201":
          description: Book created successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DataBookResponse"
        "400":
          description: Bad request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

    get:
      tags:
        - Books
      summary: List all books
      security:
        - ApiKeyAuth: []
      responses:
        "200":
          description: List of books
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DataBooksResponse"

  /books/{bookId}:
    get:
      tags:
        - Books
      summary: Get a book by ID
      security:
        - ApiKeyAuth: []
      parameters:
        - name: bookId
          in: path
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: Book detail
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DataBookResponse"
        "404":
          description: Book not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

    patch:
      tags:
        - Books
      summary: Update a book by ID
      security:
        - ApiKeyAuth: []
      parameters:
        - name: bookId
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UpdateBookRequest"
      responses:
        "200":
          description: Updated book data
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DataBookResponse"
        "400":
          description: Bad request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "404":
          description: Book not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

    delete:
      tags:
        - Books
      summary: Delete a book by ID
      security:
        - ApiKeyAuth: []
      parameters:
        - name: bookId
          in: path
          required: true
          schema:
            type: integer
      responses:
        "204":
          description: Book deleted successfully (no content)
        "404":
          description: Book not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: x-api-key

  schemas:
    # Success wrappers
    DataGuardResponse:
      type: object
      properties:
        data:
          $ref: "#/components/schemas/GuardResponse"

    DataLoginResponse:
      type: object
      properties:
        data:
          $ref: "#/components/schemas/LoginResponse"

    # Error response
    ErrorResponse:
      type: object
      properties:
        errors:
          type: string
          example: "Invalid request payload"

    # Request payloads
    RegisterGuardRequest:
      type: object
      required:
        - name
        - email
        - password
      properties:
        name:
          type: string
          example: "John Doe"
        email:
          type: string
          format: email
          example: "john@example.com"
        password:
          type: string
          format: password
          example: "strongpassword123"

    LoginGuardRequest:
      type: object
      required:
        - email
        - password
      properties:
        email:
          type: string
          format: email
          example: "john@example.com"
        password:
          type: string
          format: password
          example: "strongpassword123"

    UpdateGuardRequest:
      type: object
      properties:
        name:
          type: string
          example: "John Updated"
        password:
          type: string
          format: password
          example: "newpassword123"

    # Response payloads
    GuardResponse:
      type: object
      properties:
        id:
          type: integer
          example: 1
        name:
          type: string
          example: "John Doe"
        email:
          type: string
          format: email
          example: "john@example.com"

    LoginResponse:
      type: object
      properties:
        id:
          type: integer
          example: 1
        name:
          type: string
          example: "John Doe"
        email:
          type: string
          example: "john@example.com"
        access_token:
          type: string
          example: "example-api-key-123456"

    CreateBookRequest:
      type: object
      required:
        - title
        - author
        - stock
      properties:
        title:
          type: string
          example: "Clean Code"
        author:
          type: string
          example: "Robert C. Martin"
        stock:
          type: integer
          example: 10

    UpdateBookRequest:
      type: object
      properties:
        title:
          type: string
          example: "Clean Code Updated"
        author:
          type: string
          example: "Robert Martin"
        stock:
          type: integer
          example: 12

    # Response payloads
    BookResponse:
      type: object
      properties:
        id:
          type: integer
          example: 1
        title:
          type: string
          example: "Clean Code"
        author:
          type: string
          example: "Robert C. Martin"
        stock:
          type: integer
          example: 10

    # Success wrappers
    DataBookResponse:
      type: object
      properties:
        data:
          $ref: "#/components/schemas/BookResponse"

    DataBooksResponse:
      type: object
      properties:
        data:
          type: array
          items:
            $ref: "#/components/schemas/BookResponse"
